search_tweets_api:
  bearer_token: AAAAAAAAAAAAAAAAAAAAAOmBYgEAAAAAczWUgmeQGFjck9WASQUdsvHvuSQ%3DWOdf9l69eQcpYJFuPWbQ3foVkzmtn35ApMIwcb7wsi1T8wyidk
azure:
  subscription_key: 4378469faa8544cc84829e9ffbc6d9ff